// Generated by gencpp from file planning/GetGoalState.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_GETGOALSTATE_H
#define PLANNING_MESSAGE_GETGOALSTATE_H

#include <ros/service_traits.h>


#include <planning/GetGoalStateRequest.h>
#include <planning/GetGoalStateResponse.h>


namespace planning
{

struct GetGoalState
{

typedef GetGoalStateRequest Request;
typedef GetGoalStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGoalState
} // namespace planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning::GetGoalState > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::planning::GetGoalState&) { return value(); }
};

template<>
struct DataType< ::planning::GetGoalState > {
  static const char* value()
  {
    return "planning/GetGoalState";
  }

  static const char* value(const ::planning::GetGoalState&) { return value(); }
};


// service_traits::MD5Sum< ::planning::GetGoalStateRequest> should match 
// service_traits::MD5Sum< ::planning::GetGoalState > 
template<>
struct MD5Sum< ::planning::GetGoalStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning::GetGoalState >::value();
  }
  static const char* value(const ::planning::GetGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::GetGoalStateRequest> should match 
// service_traits::DataType< ::planning::GetGoalState > 
template<>
struct DataType< ::planning::GetGoalStateRequest>
{
  static const char* value()
  {
    return DataType< ::planning::GetGoalState >::value();
  }
  static const char* value(const ::planning::GetGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning::GetGoalStateResponse> should match 
// service_traits::MD5Sum< ::planning::GetGoalState > 
template<>
struct MD5Sum< ::planning::GetGoalStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning::GetGoalState >::value();
  }
  static const char* value(const ::planning::GetGoalStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::GetGoalStateResponse> should match 
// service_traits::DataType< ::planning::GetGoalState > 
template<>
struct DataType< ::planning::GetGoalStateResponse>
{
  static const char* value()
  {
    return DataType< ::planning::GetGoalState >::value();
  }
  static const char* value(const ::planning::GetGoalStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MESSAGE_GETGOALSTATE_H
