// Generated by gencpp from file planning/GetInitialState.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_GETINITIALSTATE_H
#define PLANNING_MESSAGE_GETINITIALSTATE_H

#include <ros/service_traits.h>


#include <planning/GetInitialStateRequest.h>
#include <planning/GetInitialStateResponse.h>


namespace planning
{

struct GetInitialState
{

typedef GetInitialStateRequest Request;
typedef GetInitialStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInitialState
} // namespace planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning::GetInitialState > {
  static const char* value()
  {
    return "3601ae784a1cdef6da6662412292fe03";
  }

  static const char* value(const ::planning::GetInitialState&) { return value(); }
};

template<>
struct DataType< ::planning::GetInitialState > {
  static const char* value()
  {
    return "planning/GetInitialState";
  }

  static const char* value(const ::planning::GetInitialState&) { return value(); }
};


// service_traits::MD5Sum< ::planning::GetInitialStateRequest> should match 
// service_traits::MD5Sum< ::planning::GetInitialState > 
template<>
struct MD5Sum< ::planning::GetInitialStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning::GetInitialState >::value();
  }
  static const char* value(const ::planning::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::GetInitialStateRequest> should match 
// service_traits::DataType< ::planning::GetInitialState > 
template<>
struct DataType< ::planning::GetInitialStateRequest>
{
  static const char* value()
  {
    return DataType< ::planning::GetInitialState >::value();
  }
  static const char* value(const ::planning::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning::GetInitialStateResponse> should match 
// service_traits::MD5Sum< ::planning::GetInitialState > 
template<>
struct MD5Sum< ::planning::GetInitialStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning::GetInitialState >::value();
  }
  static const char* value(const ::planning::GetInitialStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::GetInitialStateResponse> should match 
// service_traits::DataType< ::planning::GetInitialState > 
template<>
struct DataType< ::planning::GetInitialStateResponse>
{
  static const char* value()
  {
    return DataType< ::planning::GetInitialState >::value();
  }
  static const char* value(const ::planning::GetInitialStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MESSAGE_GETINITIALSTATE_H
