// Generated by gencpp from file planning/MoveActionMsg.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_MOVEACTIONMSG_H
#define PLANNING_MESSAGE_MOVEACTIONMSG_H

#include <ros/service_traits.h>


#include <planning/MoveActionMsgRequest.h>
#include <planning/MoveActionMsgResponse.h>


namespace planning
{

struct MoveActionMsg
{

typedef MoveActionMsgRequest Request;
typedef MoveActionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveActionMsg
} // namespace planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning::MoveActionMsg > {
  static const char* value()
  {
    return "fb4acfe02b85918b96aa76c50ea0a96e";
  }

  static const char* value(const ::planning::MoveActionMsg&) { return value(); }
};

template<>
struct DataType< ::planning::MoveActionMsg > {
  static const char* value()
  {
    return "planning/MoveActionMsg";
  }

  static const char* value(const ::planning::MoveActionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::planning::MoveActionMsgRequest> should match 
// service_traits::MD5Sum< ::planning::MoveActionMsg > 
template<>
struct MD5Sum< ::planning::MoveActionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning::MoveActionMsg >::value();
  }
  static const char* value(const ::planning::MoveActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::MoveActionMsgRequest> should match 
// service_traits::DataType< ::planning::MoveActionMsg > 
template<>
struct DataType< ::planning::MoveActionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::planning::MoveActionMsg >::value();
  }
  static const char* value(const ::planning::MoveActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning::MoveActionMsgResponse> should match 
// service_traits::MD5Sum< ::planning::MoveActionMsg > 
template<>
struct MD5Sum< ::planning::MoveActionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning::MoveActionMsg >::value();
  }
  static const char* value(const ::planning::MoveActionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::MoveActionMsgResponse> should match 
// service_traits::DataType< ::planning::MoveActionMsg > 
template<>
struct DataType< ::planning::MoveActionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::planning::MoveActionMsg >::value();
  }
  static const char* value(const ::planning::MoveActionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MESSAGE_MOVEACTIONMSG_H
