// Generated by gencpp from file planning/PickActionMsg.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_PICKACTIONMSG_H
#define PLANNING_MESSAGE_PICKACTIONMSG_H

#include <ros/service_traits.h>


#include <planning/PickActionMsgRequest.h>
#include <planning/PickActionMsgResponse.h>


namespace planning
{

struct PickActionMsg
{

typedef PickActionMsgRequest Request;
typedef PickActionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickActionMsg
} // namespace planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning::PickActionMsg > {
  static const char* value()
  {
    return "3ab27bcdd62db4306af656bdabcd225b";
  }

  static const char* value(const ::planning::PickActionMsg&) { return value(); }
};

template<>
struct DataType< ::planning::PickActionMsg > {
  static const char* value()
  {
    return "planning/PickActionMsg";
  }

  static const char* value(const ::planning::PickActionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::planning::PickActionMsgRequest> should match 
// service_traits::MD5Sum< ::planning::PickActionMsg > 
template<>
struct MD5Sum< ::planning::PickActionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning::PickActionMsg >::value();
  }
  static const char* value(const ::planning::PickActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::PickActionMsgRequest> should match 
// service_traits::DataType< ::planning::PickActionMsg > 
template<>
struct DataType< ::planning::PickActionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::planning::PickActionMsg >::value();
  }
  static const char* value(const ::planning::PickActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning::PickActionMsgResponse> should match 
// service_traits::MD5Sum< ::planning::PickActionMsg > 
template<>
struct MD5Sum< ::planning::PickActionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning::PickActionMsg >::value();
  }
  static const char* value(const ::planning::PickActionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::PickActionMsgResponse> should match 
// service_traits::DataType< ::planning::PickActionMsg > 
template<>
struct DataType< ::planning::PickActionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::planning::PickActionMsg >::value();
  }
  static const char* value(const ::planning::PickActionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MESSAGE_PICKACTIONMSG_H
