// Generated by gencpp from file planning/PickActionMsgRequest.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_PICKACTIONMSGREQUEST_H
#define PLANNING_MESSAGE_PICKACTIONMSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planning
{
template <class ContainerAllocator>
struct PickActionMsgRequest_
{
  typedef PickActionMsgRequest_<ContainerAllocator> Type;

  PickActionMsgRequest_()
    : book_name()
    , x(0.0)
    , y(0.0)
    , orientation()  {
    }
  PickActionMsgRequest_(const ContainerAllocator& _alloc)
    : book_name(_alloc)
    , x(0.0)
    , y(0.0)
    , orientation(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _book_name_type;
  _book_name_type book_name;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::planning::PickActionMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning::PickActionMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PickActionMsgRequest_

typedef ::planning::PickActionMsgRequest_<std::allocator<void> > PickActionMsgRequest;

typedef boost::shared_ptr< ::planning::PickActionMsgRequest > PickActionMsgRequestPtr;
typedef boost::shared_ptr< ::planning::PickActionMsgRequest const> PickActionMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning::PickActionMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning::PickActionMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planning::PickActionMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::PickActionMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::PickActionMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::PickActionMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::PickActionMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::PickActionMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning::PickActionMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7660ff960644fb42b1526dadbb4d22e7";
  }

  static const char* value(const ::planning::PickActionMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7660ff960644fb42ULL;
  static const uint64_t static_value2 = 0xb1526dadbb4d22e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::planning::PickActionMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning/PickActionMsgRequest";
  }

  static const char* value(const ::planning::PickActionMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning::PickActionMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string book_name\n\
float64 x\n\
float64 y\n\
string orientation\n\
";
  }

  static const char* value(const ::planning::PickActionMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning::PickActionMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.book_name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickActionMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning::PickActionMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planning::PickActionMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "book_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.book_name);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "orientation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MESSAGE_PICKACTIONMSGREQUEST_H
