// Generated by gencpp from file planning/PlaceActionMsg.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_PLACEACTIONMSG_H
#define PLANNING_MESSAGE_PLACEACTIONMSG_H

#include <ros/service_traits.h>


#include <planning/PlaceActionMsgRequest.h>
#include <planning/PlaceActionMsgResponse.h>


namespace planning
{

struct PlaceActionMsg
{

typedef PlaceActionMsgRequest Request;
typedef PlaceActionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaceActionMsg
} // namespace planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning::PlaceActionMsg > {
  static const char* value()
  {
    return "21274a3fa6a4a3f1484b941e2e263033";
  }

  static const char* value(const ::planning::PlaceActionMsg&) { return value(); }
};

template<>
struct DataType< ::planning::PlaceActionMsg > {
  static const char* value()
  {
    return "planning/PlaceActionMsg";
  }

  static const char* value(const ::planning::PlaceActionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::planning::PlaceActionMsgRequest> should match 
// service_traits::MD5Sum< ::planning::PlaceActionMsg > 
template<>
struct MD5Sum< ::planning::PlaceActionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning::PlaceActionMsg >::value();
  }
  static const char* value(const ::planning::PlaceActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::PlaceActionMsgRequest> should match 
// service_traits::DataType< ::planning::PlaceActionMsg > 
template<>
struct DataType< ::planning::PlaceActionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::planning::PlaceActionMsg >::value();
  }
  static const char* value(const ::planning::PlaceActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning::PlaceActionMsgResponse> should match 
// service_traits::MD5Sum< ::planning::PlaceActionMsg > 
template<>
struct MD5Sum< ::planning::PlaceActionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning::PlaceActionMsg >::value();
  }
  static const char* value(const ::planning::PlaceActionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::PlaceActionMsgResponse> should match 
// service_traits::DataType< ::planning::PlaceActionMsg > 
template<>
struct DataType< ::planning::PlaceActionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::planning::PlaceActionMsg >::value();
  }
  static const char* value(const ::planning::PlaceActionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MESSAGE_PLACEACTIONMSG_H
