// Generated by gencpp from file planning/RemoveBlockedEdgeMsg.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_REMOVEBLOCKEDEDGEMSG_H
#define PLANNING_MESSAGE_REMOVEBLOCKEDEDGEMSG_H

#include <ros/service_traits.h>


#include <planning/RemoveBlockedEdgeMsgRequest.h>
#include <planning/RemoveBlockedEdgeMsgResponse.h>


namespace planning
{

struct RemoveBlockedEdgeMsg
{

typedef RemoveBlockedEdgeMsgRequest Request;
typedef RemoveBlockedEdgeMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveBlockedEdgeMsg
} // namespace planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning::RemoveBlockedEdgeMsg > {
  static const char* value()
  {
    return "c991829b35c0398c16705137e62ce3d7";
  }

  static const char* value(const ::planning::RemoveBlockedEdgeMsg&) { return value(); }
};

template<>
struct DataType< ::planning::RemoveBlockedEdgeMsg > {
  static const char* value()
  {
    return "planning/RemoveBlockedEdgeMsg";
  }

  static const char* value(const ::planning::RemoveBlockedEdgeMsg&) { return value(); }
};


// service_traits::MD5Sum< ::planning::RemoveBlockedEdgeMsgRequest> should match 
// service_traits::MD5Sum< ::planning::RemoveBlockedEdgeMsg > 
template<>
struct MD5Sum< ::planning::RemoveBlockedEdgeMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::planning::RemoveBlockedEdgeMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::RemoveBlockedEdgeMsgRequest> should match 
// service_traits::DataType< ::planning::RemoveBlockedEdgeMsg > 
template<>
struct DataType< ::planning::RemoveBlockedEdgeMsgRequest>
{
  static const char* value()
  {
    return DataType< ::planning::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::planning::RemoveBlockedEdgeMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning::RemoveBlockedEdgeMsgResponse> should match 
// service_traits::MD5Sum< ::planning::RemoveBlockedEdgeMsg > 
template<>
struct MD5Sum< ::planning::RemoveBlockedEdgeMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::planning::RemoveBlockedEdgeMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::RemoveBlockedEdgeMsgResponse> should match 
// service_traits::DataType< ::planning::RemoveBlockedEdgeMsg > 
template<>
struct DataType< ::planning::RemoveBlockedEdgeMsgResponse>
{
  static const char* value()
  {
    return DataType< ::planning::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::planning::RemoveBlockedEdgeMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MESSAGE_REMOVEBLOCKEDEDGEMSG_H
