// Generated by gencpp from file group_15/GetGoalState.msg
// DO NOT EDIT!


#ifndef GROUP_15_MESSAGE_GETGOALSTATE_H
#define GROUP_15_MESSAGE_GETGOALSTATE_H

#include <ros/service_traits.h>


#include <group_15/GetGoalStateRequest.h>
#include <group_15/GetGoalStateResponse.h>


namespace group_15
{

struct GetGoalState
{

typedef GetGoalStateRequest Request;
typedef GetGoalStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGoalState
} // namespace group_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_15::GetGoalState > {
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::group_15::GetGoalState&) { return value(); }
};

template<>
struct DataType< ::group_15::GetGoalState > {
  static const char* value()
  {
    return "group_15/GetGoalState";
  }

  static const char* value(const ::group_15::GetGoalState&) { return value(); }
};


// service_traits::MD5Sum< ::group_15::GetGoalStateRequest> should match 
// service_traits::MD5Sum< ::group_15::GetGoalState > 
template<>
struct MD5Sum< ::group_15::GetGoalStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::GetGoalState >::value();
  }
  static const char* value(const ::group_15::GetGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::GetGoalStateRequest> should match 
// service_traits::DataType< ::group_15::GetGoalState > 
template<>
struct DataType< ::group_15::GetGoalStateRequest>
{
  static const char* value()
  {
    return DataType< ::group_15::GetGoalState >::value();
  }
  static const char* value(const ::group_15::GetGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_15::GetGoalStateResponse> should match 
// service_traits::MD5Sum< ::group_15::GetGoalState > 
template<>
struct MD5Sum< ::group_15::GetGoalStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::GetGoalState >::value();
  }
  static const char* value(const ::group_15::GetGoalStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::GetGoalStateResponse> should match 
// service_traits::DataType< ::group_15::GetGoalState > 
template<>
struct DataType< ::group_15::GetGoalStateResponse>
{
  static const char* value()
  {
    return DataType< ::group_15::GetGoalState >::value();
  }
  static const char* value(const ::group_15::GetGoalStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_15_MESSAGE_GETGOALSTATE_H
