// Generated by gencpp from file group_15/GetInitialState.msg
// DO NOT EDIT!


#ifndef GROUP_15_MESSAGE_GETINITIALSTATE_H
#define GROUP_15_MESSAGE_GETINITIALSTATE_H

#include <ros/service_traits.h>


#include <group_15/GetInitialStateRequest.h>
#include <group_15/GetInitialStateResponse.h>


namespace group_15
{

struct GetInitialState
{

typedef GetInitialStateRequest Request;
typedef GetInitialStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInitialState
} // namespace group_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_15::GetInitialState > {
  static const char* value()
  {
    return "3601ae784a1cdef6da6662412292fe03";
  }

  static const char* value(const ::group_15::GetInitialState&) { return value(); }
};

template<>
struct DataType< ::group_15::GetInitialState > {
  static const char* value()
  {
    return "group_15/GetInitialState";
  }

  static const char* value(const ::group_15::GetInitialState&) { return value(); }
};


// service_traits::MD5Sum< ::group_15::GetInitialStateRequest> should match 
// service_traits::MD5Sum< ::group_15::GetInitialState > 
template<>
struct MD5Sum< ::group_15::GetInitialStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::GetInitialState >::value();
  }
  static const char* value(const ::group_15::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::GetInitialStateRequest> should match 
// service_traits::DataType< ::group_15::GetInitialState > 
template<>
struct DataType< ::group_15::GetInitialStateRequest>
{
  static const char* value()
  {
    return DataType< ::group_15::GetInitialState >::value();
  }
  static const char* value(const ::group_15::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_15::GetInitialStateResponse> should match 
// service_traits::MD5Sum< ::group_15::GetInitialState > 
template<>
struct MD5Sum< ::group_15::GetInitialStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::GetInitialState >::value();
  }
  static const char* value(const ::group_15::GetInitialStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::GetInitialStateResponse> should match 
// service_traits::DataType< ::group_15::GetInitialState > 
template<>
struct DataType< ::group_15::GetInitialStateResponse>
{
  static const char* value()
  {
    return DataType< ::group_15::GetInitialState >::value();
  }
  static const char* value(const ::group_15::GetInitialStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_15_MESSAGE_GETINITIALSTATE_H
