// Generated by gencpp from file group_15/GetSuccessor.msg
// DO NOT EDIT!


#ifndef GROUP_15_MESSAGE_GETSUCCESSOR_H
#define GROUP_15_MESSAGE_GETSUCCESSOR_H

#include <ros/service_traits.h>


#include <group_15/GetSuccessorRequest.h>
#include <group_15/GetSuccessorResponse.h>


namespace group_15
{

struct GetSuccessor
{

typedef GetSuccessorRequest Request;
typedef GetSuccessorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSuccessor
} // namespace group_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_15::GetSuccessor > {
  static const char* value()
  {
    return "3f69bbdba57b08f704b0827c3651a8d8";
  }

  static const char* value(const ::group_15::GetSuccessor&) { return value(); }
};

template<>
struct DataType< ::group_15::GetSuccessor > {
  static const char* value()
  {
    return "group_15/GetSuccessor";
  }

  static const char* value(const ::group_15::GetSuccessor&) { return value(); }
};


// service_traits::MD5Sum< ::group_15::GetSuccessorRequest> should match 
// service_traits::MD5Sum< ::group_15::GetSuccessor > 
template<>
struct MD5Sum< ::group_15::GetSuccessorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::GetSuccessor >::value();
  }
  static const char* value(const ::group_15::GetSuccessorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::GetSuccessorRequest> should match 
// service_traits::DataType< ::group_15::GetSuccessor > 
template<>
struct DataType< ::group_15::GetSuccessorRequest>
{
  static const char* value()
  {
    return DataType< ::group_15::GetSuccessor >::value();
  }
  static const char* value(const ::group_15::GetSuccessorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_15::GetSuccessorResponse> should match 
// service_traits::MD5Sum< ::group_15::GetSuccessor > 
template<>
struct MD5Sum< ::group_15::GetSuccessorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::GetSuccessor >::value();
  }
  static const char* value(const ::group_15::GetSuccessorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::GetSuccessorResponse> should match 
// service_traits::DataType< ::group_15::GetSuccessor > 
template<>
struct DataType< ::group_15::GetSuccessorResponse>
{
  static const char* value()
  {
    return DataType< ::group_15::GetSuccessor >::value();
  }
  static const char* value(const ::group_15::GetSuccessorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_15_MESSAGE_GETSUCCESSOR_H
