// Generated by gencpp from file group_15/IsGoalState.msg
// DO NOT EDIT!


#ifndef GROUP_15_MESSAGE_ISGOALSTATE_H
#define GROUP_15_MESSAGE_ISGOALSTATE_H

#include <ros/service_traits.h>


#include <group_15/IsGoalStateRequest.h>
#include <group_15/IsGoalStateResponse.h>


namespace group_15
{

struct IsGoalState
{

typedef IsGoalStateRequest Request;
typedef IsGoalStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsGoalState
} // namespace group_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_15::IsGoalState > {
  static const char* value()
  {
    return "b368a2d5da7c88f49d77eafba906c151";
  }

  static const char* value(const ::group_15::IsGoalState&) { return value(); }
};

template<>
struct DataType< ::group_15::IsGoalState > {
  static const char* value()
  {
    return "group_15/IsGoalState";
  }

  static const char* value(const ::group_15::IsGoalState&) { return value(); }
};


// service_traits::MD5Sum< ::group_15::IsGoalStateRequest> should match 
// service_traits::MD5Sum< ::group_15::IsGoalState > 
template<>
struct MD5Sum< ::group_15::IsGoalStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::IsGoalState >::value();
  }
  static const char* value(const ::group_15::IsGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::IsGoalStateRequest> should match 
// service_traits::DataType< ::group_15::IsGoalState > 
template<>
struct DataType< ::group_15::IsGoalStateRequest>
{
  static const char* value()
  {
    return DataType< ::group_15::IsGoalState >::value();
  }
  static const char* value(const ::group_15::IsGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_15::IsGoalStateResponse> should match 
// service_traits::MD5Sum< ::group_15::IsGoalState > 
template<>
struct MD5Sum< ::group_15::IsGoalStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::IsGoalState >::value();
  }
  static const char* value(const ::group_15::IsGoalStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::IsGoalStateResponse> should match 
// service_traits::DataType< ::group_15::IsGoalState > 
template<>
struct DataType< ::group_15::IsGoalStateResponse>
{
  static const char* value()
  {
    return DataType< ::group_15::IsGoalState >::value();
  }
  static const char* value(const ::group_15::IsGoalStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_15_MESSAGE_ISGOALSTATE_H
