// Generated by gencpp from file group_15/MoveActionMsg.msg
// DO NOT EDIT!


#ifndef GROUP_15_MESSAGE_MOVEACTIONMSG_H
#define GROUP_15_MESSAGE_MOVEACTIONMSG_H

#include <ros/service_traits.h>


#include <group_15/MoveActionMsgRequest.h>
#include <group_15/MoveActionMsgResponse.h>


namespace group_15
{

struct MoveActionMsg
{

typedef MoveActionMsgRequest Request;
typedef MoveActionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveActionMsg
} // namespace group_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_15::MoveActionMsg > {
  static const char* value()
  {
    return "fb4acfe02b85918b96aa76c50ea0a96e";
  }

  static const char* value(const ::group_15::MoveActionMsg&) { return value(); }
};

template<>
struct DataType< ::group_15::MoveActionMsg > {
  static const char* value()
  {
    return "group_15/MoveActionMsg";
  }

  static const char* value(const ::group_15::MoveActionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::group_15::MoveActionMsgRequest> should match 
// service_traits::MD5Sum< ::group_15::MoveActionMsg > 
template<>
struct MD5Sum< ::group_15::MoveActionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::MoveActionMsg >::value();
  }
  static const char* value(const ::group_15::MoveActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::MoveActionMsgRequest> should match 
// service_traits::DataType< ::group_15::MoveActionMsg > 
template<>
struct DataType< ::group_15::MoveActionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::group_15::MoveActionMsg >::value();
  }
  static const char* value(const ::group_15::MoveActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_15::MoveActionMsgResponse> should match 
// service_traits::MD5Sum< ::group_15::MoveActionMsg > 
template<>
struct MD5Sum< ::group_15::MoveActionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::MoveActionMsg >::value();
  }
  static const char* value(const ::group_15::MoveActionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::MoveActionMsgResponse> should match 
// service_traits::DataType< ::group_15::MoveActionMsg > 
template<>
struct DataType< ::group_15::MoveActionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::group_15::MoveActionMsg >::value();
  }
  static const char* value(const ::group_15::MoveActionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_15_MESSAGE_MOVEACTIONMSG_H
