// Generated by gencpp from file group_15/PickActionMsg.msg
// DO NOT EDIT!


#ifndef GROUP_15_MESSAGE_PICKACTIONMSG_H
#define GROUP_15_MESSAGE_PICKACTIONMSG_H

#include <ros/service_traits.h>


#include <group_15/PickActionMsgRequest.h>
#include <group_15/PickActionMsgResponse.h>


namespace group_15
{

struct PickActionMsg
{

typedef PickActionMsgRequest Request;
typedef PickActionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickActionMsg
} // namespace group_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_15::PickActionMsg > {
  static const char* value()
  {
    return "5ff8f292aa2f93cdfaa54c03c101cdb3";
  }

  static const char* value(const ::group_15::PickActionMsg&) { return value(); }
};

template<>
struct DataType< ::group_15::PickActionMsg > {
  static const char* value()
  {
    return "group_15/PickActionMsg";
  }

  static const char* value(const ::group_15::PickActionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::group_15::PickActionMsgRequest> should match 
// service_traits::MD5Sum< ::group_15::PickActionMsg > 
template<>
struct MD5Sum< ::group_15::PickActionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::PickActionMsg >::value();
  }
  static const char* value(const ::group_15::PickActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::PickActionMsgRequest> should match 
// service_traits::DataType< ::group_15::PickActionMsg > 
template<>
struct DataType< ::group_15::PickActionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::group_15::PickActionMsg >::value();
  }
  static const char* value(const ::group_15::PickActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_15::PickActionMsgResponse> should match 
// service_traits::MD5Sum< ::group_15::PickActionMsg > 
template<>
struct MD5Sum< ::group_15::PickActionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::PickActionMsg >::value();
  }
  static const char* value(const ::group_15::PickActionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::PickActionMsgResponse> should match 
// service_traits::DataType< ::group_15::PickActionMsg > 
template<>
struct DataType< ::group_15::PickActionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::group_15::PickActionMsg >::value();
  }
  static const char* value(const ::group_15::PickActionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_15_MESSAGE_PICKACTIONMSG_H
