// Generated by gencpp from file group_15/PlaceActionMsg.msg
// DO NOT EDIT!


#ifndef GROUP_15_MESSAGE_PLACEACTIONMSG_H
#define GROUP_15_MESSAGE_PLACEACTIONMSG_H

#include <ros/service_traits.h>


#include <group_15/PlaceActionMsgRequest.h>
#include <group_15/PlaceActionMsgResponse.h>


namespace group_15
{

struct PlaceActionMsg
{

typedef PlaceActionMsgRequest Request;
typedef PlaceActionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaceActionMsg
} // namespace group_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_15::PlaceActionMsg > {
  static const char* value()
  {
    return "802052ffdbb8c2b43280d7202fd0b983";
  }

  static const char* value(const ::group_15::PlaceActionMsg&) { return value(); }
};

template<>
struct DataType< ::group_15::PlaceActionMsg > {
  static const char* value()
  {
    return "group_15/PlaceActionMsg";
  }

  static const char* value(const ::group_15::PlaceActionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::group_15::PlaceActionMsgRequest> should match 
// service_traits::MD5Sum< ::group_15::PlaceActionMsg > 
template<>
struct MD5Sum< ::group_15::PlaceActionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::PlaceActionMsg >::value();
  }
  static const char* value(const ::group_15::PlaceActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::PlaceActionMsgRequest> should match 
// service_traits::DataType< ::group_15::PlaceActionMsg > 
template<>
struct DataType< ::group_15::PlaceActionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::group_15::PlaceActionMsg >::value();
  }
  static const char* value(const ::group_15::PlaceActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_15::PlaceActionMsgResponse> should match 
// service_traits::MD5Sum< ::group_15::PlaceActionMsg > 
template<>
struct MD5Sum< ::group_15::PlaceActionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::PlaceActionMsg >::value();
  }
  static const char* value(const ::group_15::PlaceActionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::PlaceActionMsgResponse> should match 
// service_traits::DataType< ::group_15::PlaceActionMsg > 
template<>
struct DataType< ::group_15::PlaceActionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::group_15::PlaceActionMsg >::value();
  }
  static const char* value(const ::group_15::PlaceActionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_15_MESSAGE_PLACEACTIONMSG_H
