// Generated by gencpp from file group_15/RemoveBlockedEdgeMsg.msg
// DO NOT EDIT!


#ifndef GROUP_15_MESSAGE_REMOVEBLOCKEDEDGEMSG_H
#define GROUP_15_MESSAGE_REMOVEBLOCKEDEDGEMSG_H

#include <ros/service_traits.h>


#include <group_15/RemoveBlockedEdgeMsgRequest.h>
#include <group_15/RemoveBlockedEdgeMsgResponse.h>


namespace group_15
{

struct RemoveBlockedEdgeMsg
{

typedef RemoveBlockedEdgeMsgRequest Request;
typedef RemoveBlockedEdgeMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveBlockedEdgeMsg
} // namespace group_15


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_15::RemoveBlockedEdgeMsg > {
  static const char* value()
  {
    return "0f0367b18a799bf48809c710a3edf27a";
  }

  static const char* value(const ::group_15::RemoveBlockedEdgeMsg&) { return value(); }
};

template<>
struct DataType< ::group_15::RemoveBlockedEdgeMsg > {
  static const char* value()
  {
    return "group_15/RemoveBlockedEdgeMsg";
  }

  static const char* value(const ::group_15::RemoveBlockedEdgeMsg&) { return value(); }
};


// service_traits::MD5Sum< ::group_15::RemoveBlockedEdgeMsgRequest> should match 
// service_traits::MD5Sum< ::group_15::RemoveBlockedEdgeMsg > 
template<>
struct MD5Sum< ::group_15::RemoveBlockedEdgeMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::group_15::RemoveBlockedEdgeMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::RemoveBlockedEdgeMsgRequest> should match 
// service_traits::DataType< ::group_15::RemoveBlockedEdgeMsg > 
template<>
struct DataType< ::group_15::RemoveBlockedEdgeMsgRequest>
{
  static const char* value()
  {
    return DataType< ::group_15::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::group_15::RemoveBlockedEdgeMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_15::RemoveBlockedEdgeMsgResponse> should match 
// service_traits::MD5Sum< ::group_15::RemoveBlockedEdgeMsg > 
template<>
struct MD5Sum< ::group_15::RemoveBlockedEdgeMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_15::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::group_15::RemoveBlockedEdgeMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_15::RemoveBlockedEdgeMsgResponse> should match 
// service_traits::DataType< ::group_15::RemoveBlockedEdgeMsg > 
template<>
struct DataType< ::group_15::RemoveBlockedEdgeMsgResponse>
{
  static const char* value()
  {
    return DataType< ::group_15::RemoveBlockedEdgeMsg >::value();
  }
  static const char* value(const ::group_15::RemoveBlockedEdgeMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_15_MESSAGE_REMOVEBLOCKEDEDGEMSG_H
