// Generated by gencpp from file search/GetInitialState.msg
// DO NOT EDIT!


#ifndef SEARCH_MESSAGE_GETINITIALSTATE_H
#define SEARCH_MESSAGE_GETINITIALSTATE_H

#include <ros/service_traits.h>


#include <search/GetInitialStateRequest.h>
#include <search/GetInitialStateResponse.h>


namespace search
{

struct GetInitialState
{

typedef GetInitialStateRequest Request;
typedef GetInitialStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInitialState
} // namespace search


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::search::GetInitialState > {
  static const char* value()
  {
    return "3601ae784a1cdef6da6662412292fe03";
  }

  static const char* value(const ::search::GetInitialState&) { return value(); }
};

template<>
struct DataType< ::search::GetInitialState > {
  static const char* value()
  {
    return "search/GetInitialState";
  }

  static const char* value(const ::search::GetInitialState&) { return value(); }
};


// service_traits::MD5Sum< ::search::GetInitialStateRequest> should match 
// service_traits::MD5Sum< ::search::GetInitialState > 
template<>
struct MD5Sum< ::search::GetInitialStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::search::GetInitialState >::value();
  }
  static const char* value(const ::search::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::search::GetInitialStateRequest> should match 
// service_traits::DataType< ::search::GetInitialState > 
template<>
struct DataType< ::search::GetInitialStateRequest>
{
  static const char* value()
  {
    return DataType< ::search::GetInitialState >::value();
  }
  static const char* value(const ::search::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::search::GetInitialStateResponse> should match 
// service_traits::MD5Sum< ::search::GetInitialState > 
template<>
struct MD5Sum< ::search::GetInitialStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::search::GetInitialState >::value();
  }
  static const char* value(const ::search::GetInitialStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::search::GetInitialStateResponse> should match 
// service_traits::DataType< ::search::GetInitialState > 
template<>
struct DataType< ::search::GetInitialStateResponse>
{
  static const char* value()
  {
    return DataType< ::search::GetInitialState >::value();
  }
  static const char* value(const ::search::GetInitialStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEARCH_MESSAGE_GETINITIALSTATE_H
