// Generated by gencpp from file search/GetSuccessorRequest.msg
// DO NOT EDIT!


#ifndef SEARCH_MESSAGE_GETSUCCESSORREQUEST_H
#define SEARCH_MESSAGE_GETSUCCESSORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace search
{
template <class ContainerAllocator>
struct GetSuccessorRequest_
{
  typedef GetSuccessorRequest_<ContainerAllocator> Type;

  GetSuccessorRequest_()
    : x(0.0)
    , y(0.0)
    , direction()  {
    }
  GetSuccessorRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::search::GetSuccessorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::search::GetSuccessorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSuccessorRequest_

typedef ::search::GetSuccessorRequest_<std::allocator<void> > GetSuccessorRequest;

typedef boost::shared_ptr< ::search::GetSuccessorRequest > GetSuccessorRequestPtr;
typedef boost::shared_ptr< ::search::GetSuccessorRequest const> GetSuccessorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::search::GetSuccessorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::search::GetSuccessorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace search

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::search::GetSuccessorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search::GetSuccessorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::search::GetSuccessorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::search::GetSuccessorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search::GetSuccessorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search::GetSuccessorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::search::GetSuccessorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3601ae784a1cdef6da6662412292fe03";
  }

  static const char* value(const ::search::GetSuccessorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3601ae784a1cdef6ULL;
  static const uint64_t static_value2 = 0xda6662412292fe03ULL;
};

template<class ContainerAllocator>
struct DataType< ::search::GetSuccessorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "search/GetSuccessorRequest";
  }

  static const char* value(const ::search::GetSuccessorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::search::GetSuccessorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
string direction\n\
";
  }

  static const char* value(const ::search::GetSuccessorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::search::GetSuccessorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSuccessorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::search::GetSuccessorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::search::GetSuccessorRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEARCH_MESSAGE_GETSUCCESSORREQUEST_H
