// Generated by gencpp from file search/GetSuccessor.msg
// DO NOT EDIT!


#ifndef SEARCH_MESSAGE_GETSUCCESSOR_H
#define SEARCH_MESSAGE_GETSUCCESSOR_H

#include <ros/service_traits.h>


#include <search/GetSuccessorRequest.h>
#include <search/GetSuccessorResponse.h>


namespace search
{

struct GetSuccessor
{

typedef GetSuccessorRequest Request;
typedef GetSuccessorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSuccessor
} // namespace search


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::search::GetSuccessor > {
  static const char* value()
  {
    return "56c94847518b0fe4a51bc026c1190594";
  }

  static const char* value(const ::search::GetSuccessor&) { return value(); }
};

template<>
struct DataType< ::search::GetSuccessor > {
  static const char* value()
  {
    return "search/GetSuccessor";
  }

  static const char* value(const ::search::GetSuccessor&) { return value(); }
};


// service_traits::MD5Sum< ::search::GetSuccessorRequest> should match 
// service_traits::MD5Sum< ::search::GetSuccessor > 
template<>
struct MD5Sum< ::search::GetSuccessorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::search::GetSuccessor >::value();
  }
  static const char* value(const ::search::GetSuccessorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::search::GetSuccessorRequest> should match 
// service_traits::DataType< ::search::GetSuccessor > 
template<>
struct DataType< ::search::GetSuccessorRequest>
{
  static const char* value()
  {
    return DataType< ::search::GetSuccessor >::value();
  }
  static const char* value(const ::search::GetSuccessorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::search::GetSuccessorResponse> should match 
// service_traits::MD5Sum< ::search::GetSuccessor > 
template<>
struct MD5Sum< ::search::GetSuccessorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::search::GetSuccessor >::value();
  }
  static const char* value(const ::search::GetSuccessorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::search::GetSuccessorResponse> should match 
// service_traits::DataType< ::search::GetSuccessor > 
template<>
struct DataType< ::search::GetSuccessorResponse>
{
  static const char* value()
  {
    return DataType< ::search::GetSuccessor >::value();
  }
  static const char* value(const ::search::GetSuccessorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEARCH_MESSAGE_GETSUCCESSOR_H
