// Generated by gencpp from file search/IsGoalState.msg
// DO NOT EDIT!


#ifndef SEARCH_MESSAGE_ISGOALSTATE_H
#define SEARCH_MESSAGE_ISGOALSTATE_H

#include <ros/service_traits.h>


#include <search/IsGoalStateRequest.h>
#include <search/IsGoalStateResponse.h>


namespace search
{

struct IsGoalState
{

typedef IsGoalStateRequest Request;
typedef IsGoalStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsGoalState
} // namespace search


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::search::IsGoalState > {
  static const char* value()
  {
    return "b368a2d5da7c88f49d77eafba906c151";
  }

  static const char* value(const ::search::IsGoalState&) { return value(); }
};

template<>
struct DataType< ::search::IsGoalState > {
  static const char* value()
  {
    return "search/IsGoalState";
  }

  static const char* value(const ::search::IsGoalState&) { return value(); }
};


// service_traits::MD5Sum< ::search::IsGoalStateRequest> should match 
// service_traits::MD5Sum< ::search::IsGoalState > 
template<>
struct MD5Sum< ::search::IsGoalStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::search::IsGoalState >::value();
  }
  static const char* value(const ::search::IsGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::search::IsGoalStateRequest> should match 
// service_traits::DataType< ::search::IsGoalState > 
template<>
struct DataType< ::search::IsGoalStateRequest>
{
  static const char* value()
  {
    return DataType< ::search::IsGoalState >::value();
  }
  static const char* value(const ::search::IsGoalStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::search::IsGoalStateResponse> should match 
// service_traits::MD5Sum< ::search::IsGoalState > 
template<>
struct MD5Sum< ::search::IsGoalStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::search::IsGoalState >::value();
  }
  static const char* value(const ::search::IsGoalStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::search::IsGoalStateResponse> should match 
// service_traits::DataType< ::search::IsGoalState > 
template<>
struct DataType< ::search::IsGoalStateResponse>
{
  static const char* value()
  {
    return DataType< ::search::IsGoalState >::value();
  }
  static const char* value(const ::search::IsGoalStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEARCH_MESSAGE_ISGOALSTATE_H
