(cl:defpackage search-srv
  (:use )
  (:export
   "GETGOALSTATE"
   "<GETGOALSTATE-REQUEST>"
   "GETGOALSTATE-REQUEST"
   "<GETGOALSTATE-RESPONSE>"
   "GETGOALSTATE-RESPONSE"
   "GETINITIALSTATE"
   "<GETINITIALSTATE-REQUEST>"
   "GETINITIALSTATE-REQUEST"
   "<GETINITIALSTATE-RESPONSE>"
   "GETINITIALSTATE-RESPONSE"
   "GETSUCCESSOR"
   "<GETSUCCESSOR-REQUEST>"
   "GETSUCCESSOR-REQUEST"
   "<GETSUCCESSOR-RESPONSE>"
   "GETSUCCESSOR-RESPONSE"
   "ISGOALSTATE"
   "<ISGOALSTATE-REQUEST>"
   "ISGOALSTATE-REQUEST"
   "<ISGOALSTATE-RESPONSE>"
   "ISGOALSTATE-RESPONSE"
  ))

