// Generated by gencpp from file reinforcement/ActionMsg.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_MESSAGE_ACTIONMSG_H
#define REINFORCEMENT_MESSAGE_ACTIONMSG_H

#include <ros/service_traits.h>


#include <reinforcement/ActionMsgRequest.h>
#include <reinforcement/ActionMsgResponse.h>


namespace reinforcement
{

struct ActionMsg
{

typedef ActionMsgRequest Request;
typedef ActionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionMsg
} // namespace reinforcement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reinforcement::ActionMsg > {
  static const char* value()
  {
    return "dfdaf84421aa9323fca0ea8f7917a197";
  }

  static const char* value(const ::reinforcement::ActionMsg&) { return value(); }
};

template<>
struct DataType< ::reinforcement::ActionMsg > {
  static const char* value()
  {
    return "reinforcement/ActionMsg";
  }

  static const char* value(const ::reinforcement::ActionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::reinforcement::ActionMsgRequest> should match 
// service_traits::MD5Sum< ::reinforcement::ActionMsg > 
template<>
struct MD5Sum< ::reinforcement::ActionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::ActionMsg >::value();
  }
  static const char* value(const ::reinforcement::ActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::ActionMsgRequest> should match 
// service_traits::DataType< ::reinforcement::ActionMsg > 
template<>
struct DataType< ::reinforcement::ActionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::reinforcement::ActionMsg >::value();
  }
  static const char* value(const ::reinforcement::ActionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reinforcement::ActionMsgResponse> should match 
// service_traits::MD5Sum< ::reinforcement::ActionMsg > 
template<>
struct MD5Sum< ::reinforcement::ActionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::ActionMsg >::value();
  }
  static const char* value(const ::reinforcement::ActionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::ActionMsgResponse> should match 
// service_traits::DataType< ::reinforcement::ActionMsg > 
template<>
struct DataType< ::reinforcement::ActionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::reinforcement::ActionMsg >::value();
  }
  static const char* value(const ::reinforcement::ActionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REINFORCEMENT_MESSAGE_ACTIONMSG_H
