// Generated by gencpp from file reinforcement/GetInitialState.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_MESSAGE_GETINITIALSTATE_H
#define REINFORCEMENT_MESSAGE_GETINITIALSTATE_H

#include <ros/service_traits.h>


#include <reinforcement/GetInitialStateRequest.h>
#include <reinforcement/GetInitialStateResponse.h>


namespace reinforcement
{

struct GetInitialState
{

typedef GetInitialStateRequest Request;
typedef GetInitialStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInitialState
} // namespace reinforcement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reinforcement::GetInitialState > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::reinforcement::GetInitialState&) { return value(); }
};

template<>
struct DataType< ::reinforcement::GetInitialState > {
  static const char* value()
  {
    return "reinforcement/GetInitialState";
  }

  static const char* value(const ::reinforcement::GetInitialState&) { return value(); }
};


// service_traits::MD5Sum< ::reinforcement::GetInitialStateRequest> should match 
// service_traits::MD5Sum< ::reinforcement::GetInitialState > 
template<>
struct MD5Sum< ::reinforcement::GetInitialStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::GetInitialState >::value();
  }
  static const char* value(const ::reinforcement::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::GetInitialStateRequest> should match 
// service_traits::DataType< ::reinforcement::GetInitialState > 
template<>
struct DataType< ::reinforcement::GetInitialStateRequest>
{
  static const char* value()
  {
    return DataType< ::reinforcement::GetInitialState >::value();
  }
  static const char* value(const ::reinforcement::GetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reinforcement::GetInitialStateResponse> should match 
// service_traits::MD5Sum< ::reinforcement::GetInitialState > 
template<>
struct MD5Sum< ::reinforcement::GetInitialStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::GetInitialState >::value();
  }
  static const char* value(const ::reinforcement::GetInitialStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::GetInitialStateResponse> should match 
// service_traits::DataType< ::reinforcement::GetInitialState > 
template<>
struct DataType< ::reinforcement::GetInitialStateResponse>
{
  static const char* value()
  {
    return DataType< ::reinforcement::GetInitialState >::value();
  }
  static const char* value(const ::reinforcement::GetInitialStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REINFORCEMENT_MESSAGE_GETINITIALSTATE_H
