// Generated by gencpp from file reinforcement/GetPossibleActions.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_MESSAGE_GETPOSSIBLEACTIONS_H
#define REINFORCEMENT_MESSAGE_GETPOSSIBLEACTIONS_H

#include <ros/service_traits.h>


#include <reinforcement/GetPossibleActionsRequest.h>
#include <reinforcement/GetPossibleActionsResponse.h>


namespace reinforcement
{

struct GetPossibleActions
{

typedef GetPossibleActionsRequest Request;
typedef GetPossibleActionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPossibleActions
} // namespace reinforcement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reinforcement::GetPossibleActions > {
  static const char* value()
  {
    return "6b2bdb080846c43b9c1353f9cdd5a8a5";
  }

  static const char* value(const ::reinforcement::GetPossibleActions&) { return value(); }
};

template<>
struct DataType< ::reinforcement::GetPossibleActions > {
  static const char* value()
  {
    return "reinforcement/GetPossibleActions";
  }

  static const char* value(const ::reinforcement::GetPossibleActions&) { return value(); }
};


// service_traits::MD5Sum< ::reinforcement::GetPossibleActionsRequest> should match 
// service_traits::MD5Sum< ::reinforcement::GetPossibleActions > 
template<>
struct MD5Sum< ::reinforcement::GetPossibleActionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::GetPossibleActions >::value();
  }
  static const char* value(const ::reinforcement::GetPossibleActionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::GetPossibleActionsRequest> should match 
// service_traits::DataType< ::reinforcement::GetPossibleActions > 
template<>
struct DataType< ::reinforcement::GetPossibleActionsRequest>
{
  static const char* value()
  {
    return DataType< ::reinforcement::GetPossibleActions >::value();
  }
  static const char* value(const ::reinforcement::GetPossibleActionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reinforcement::GetPossibleActionsResponse> should match 
// service_traits::MD5Sum< ::reinforcement::GetPossibleActions > 
template<>
struct MD5Sum< ::reinforcement::GetPossibleActionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::GetPossibleActions >::value();
  }
  static const char* value(const ::reinforcement::GetPossibleActionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::GetPossibleActionsResponse> should match 
// service_traits::DataType< ::reinforcement::GetPossibleActions > 
template<>
struct DataType< ::reinforcement::GetPossibleActionsResponse>
{
  static const char* value()
  {
    return DataType< ::reinforcement::GetPossibleActions >::value();
  }
  static const char* value(const ::reinforcement::GetPossibleActionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REINFORCEMENT_MESSAGE_GETPOSSIBLEACTIONS_H
