// Generated by gencpp from file reinforcement/GetPossibleStates.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_MESSAGE_GETPOSSIBLESTATES_H
#define REINFORCEMENT_MESSAGE_GETPOSSIBLESTATES_H

#include <ros/service_traits.h>


#include <reinforcement/GetPossibleStatesRequest.h>
#include <reinforcement/GetPossibleStatesResponse.h>


namespace reinforcement
{

struct GetPossibleStates
{

typedef GetPossibleStatesRequest Request;
typedef GetPossibleStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPossibleStates
} // namespace reinforcement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reinforcement::GetPossibleStates > {
  static const char* value()
  {
    return "ad5e6ede9037ccf3c74ff16323c7ca34";
  }

  static const char* value(const ::reinforcement::GetPossibleStates&) { return value(); }
};

template<>
struct DataType< ::reinforcement::GetPossibleStates > {
  static const char* value()
  {
    return "reinforcement/GetPossibleStates";
  }

  static const char* value(const ::reinforcement::GetPossibleStates&) { return value(); }
};


// service_traits::MD5Sum< ::reinforcement::GetPossibleStatesRequest> should match 
// service_traits::MD5Sum< ::reinforcement::GetPossibleStates > 
template<>
struct MD5Sum< ::reinforcement::GetPossibleStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::GetPossibleStates >::value();
  }
  static const char* value(const ::reinforcement::GetPossibleStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::GetPossibleStatesRequest> should match 
// service_traits::DataType< ::reinforcement::GetPossibleStates > 
template<>
struct DataType< ::reinforcement::GetPossibleStatesRequest>
{
  static const char* value()
  {
    return DataType< ::reinforcement::GetPossibleStates >::value();
  }
  static const char* value(const ::reinforcement::GetPossibleStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reinforcement::GetPossibleStatesResponse> should match 
// service_traits::MD5Sum< ::reinforcement::GetPossibleStates > 
template<>
struct MD5Sum< ::reinforcement::GetPossibleStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::GetPossibleStates >::value();
  }
  static const char* value(const ::reinforcement::GetPossibleStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::GetPossibleStatesResponse> should match 
// service_traits::DataType< ::reinforcement::GetPossibleStates > 
template<>
struct DataType< ::reinforcement::GetPossibleStatesResponse>
{
  static const char* value()
  {
    return DataType< ::reinforcement::GetPossibleStates >::value();
  }
  static const char* value(const ::reinforcement::GetPossibleStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REINFORCEMENT_MESSAGE_GETPOSSIBLESTATES_H
