// Generated by gencpp from file reinforcement/GetReward.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_MESSAGE_GETREWARD_H
#define REINFORCEMENT_MESSAGE_GETREWARD_H

#include <ros/service_traits.h>


#include <reinforcement/GetRewardRequest.h>
#include <reinforcement/GetRewardResponse.h>


namespace reinforcement
{

struct GetReward
{

typedef GetRewardRequest Request;
typedef GetRewardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetReward
} // namespace reinforcement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reinforcement::GetReward > {
  static const char* value()
  {
    return "5db7b1f3b0b303c537d7253bf7a2c047";
  }

  static const char* value(const ::reinforcement::GetReward&) { return value(); }
};

template<>
struct DataType< ::reinforcement::GetReward > {
  static const char* value()
  {
    return "reinforcement/GetReward";
  }

  static const char* value(const ::reinforcement::GetReward&) { return value(); }
};


// service_traits::MD5Sum< ::reinforcement::GetRewardRequest> should match 
// service_traits::MD5Sum< ::reinforcement::GetReward > 
template<>
struct MD5Sum< ::reinforcement::GetRewardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::GetReward >::value();
  }
  static const char* value(const ::reinforcement::GetRewardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::GetRewardRequest> should match 
// service_traits::DataType< ::reinforcement::GetReward > 
template<>
struct DataType< ::reinforcement::GetRewardRequest>
{
  static const char* value()
  {
    return DataType< ::reinforcement::GetReward >::value();
  }
  static const char* value(const ::reinforcement::GetRewardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reinforcement::GetRewardResponse> should match 
// service_traits::MD5Sum< ::reinforcement::GetReward > 
template<>
struct MD5Sum< ::reinforcement::GetRewardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::GetReward >::value();
  }
  static const char* value(const ::reinforcement::GetRewardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::GetRewardResponse> should match 
// service_traits::DataType< ::reinforcement::GetReward > 
template<>
struct DataType< ::reinforcement::GetRewardResponse>
{
  static const char* value()
  {
    return DataType< ::reinforcement::GetReward >::value();
  }
  static const char* value(const ::reinforcement::GetRewardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REINFORCEMENT_MESSAGE_GETREWARD_H
