// Generated by gencpp from file reinforcement/IsTerminalStateResponse.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_MESSAGE_ISTERMINALSTATERESPONSE_H
#define REINFORCEMENT_MESSAGE_ISTERMINALSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reinforcement
{
template <class ContainerAllocator>
struct IsTerminalStateResponse_
{
  typedef IsTerminalStateResponse_<ContainerAllocator> Type;

  IsTerminalStateResponse_()
    : value(0)  {
    }
  IsTerminalStateResponse_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsTerminalStateResponse_

typedef ::reinforcement::IsTerminalStateResponse_<std::allocator<void> > IsTerminalStateResponse;

typedef boost::shared_ptr< ::reinforcement::IsTerminalStateResponse > IsTerminalStateResponsePtr;
typedef boost::shared_ptr< ::reinforcement::IsTerminalStateResponse const> IsTerminalStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reinforcement

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const ::reinforcement::IsTerminalStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3087778e93fcd34ULL;
  static const uint64_t static_value2 = 0xcc8d65bc54e850d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reinforcement/IsTerminalStateResponse";
  }

  static const char* value(const ::reinforcement::IsTerminalStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 value\n\
";
  }

  static const char* value(const ::reinforcement::IsTerminalStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsTerminalStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reinforcement::IsTerminalStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reinforcement::IsTerminalStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REINFORCEMENT_MESSAGE_ISTERMINALSTATERESPONSE_H
