// Generated by gencpp from file reinforcement/IsTerminalState.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_MESSAGE_ISTERMINALSTATE_H
#define REINFORCEMENT_MESSAGE_ISTERMINALSTATE_H

#include <ros/service_traits.h>


#include <reinforcement/IsTerminalStateRequest.h>
#include <reinforcement/IsTerminalStateResponse.h>


namespace reinforcement
{

struct IsTerminalState
{

typedef IsTerminalStateRequest Request;
typedef IsTerminalStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsTerminalState
} // namespace reinforcement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reinforcement::IsTerminalState > {
  static const char* value()
  {
    return "f7b1a4100171db94609b126295dd4151";
  }

  static const char* value(const ::reinforcement::IsTerminalState&) { return value(); }
};

template<>
struct DataType< ::reinforcement::IsTerminalState > {
  static const char* value()
  {
    return "reinforcement/IsTerminalState";
  }

  static const char* value(const ::reinforcement::IsTerminalState&) { return value(); }
};


// service_traits::MD5Sum< ::reinforcement::IsTerminalStateRequest> should match 
// service_traits::MD5Sum< ::reinforcement::IsTerminalState > 
template<>
struct MD5Sum< ::reinforcement::IsTerminalStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::IsTerminalState >::value();
  }
  static const char* value(const ::reinforcement::IsTerminalStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::IsTerminalStateRequest> should match 
// service_traits::DataType< ::reinforcement::IsTerminalState > 
template<>
struct DataType< ::reinforcement::IsTerminalStateRequest>
{
  static const char* value()
  {
    return DataType< ::reinforcement::IsTerminalState >::value();
  }
  static const char* value(const ::reinforcement::IsTerminalStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reinforcement::IsTerminalStateResponse> should match 
// service_traits::MD5Sum< ::reinforcement::IsTerminalState > 
template<>
struct MD5Sum< ::reinforcement::IsTerminalStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::IsTerminalState >::value();
  }
  static const char* value(const ::reinforcement::IsTerminalStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::IsTerminalStateResponse> should match 
// service_traits::DataType< ::reinforcement::IsTerminalState > 
template<>
struct DataType< ::reinforcement::IsTerminalStateResponse>
{
  static const char* value()
  {
    return DataType< ::reinforcement::IsTerminalState >::value();
  }
  static const char* value(const ::reinforcement::IsTerminalStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REINFORCEMENT_MESSAGE_ISTERMINALSTATE_H
