// Generated by gencpp from file reinforcement/ResetWorldMsg.msg
// DO NOT EDIT!


#ifndef REINFORCEMENT_MESSAGE_RESETWORLDMSG_H
#define REINFORCEMENT_MESSAGE_RESETWORLDMSG_H

#include <ros/service_traits.h>


#include <reinforcement/ResetWorldMsgRequest.h>
#include <reinforcement/ResetWorldMsgResponse.h>


namespace reinforcement
{

struct ResetWorldMsg
{

typedef ResetWorldMsgRequest Request;
typedef ResetWorldMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetWorldMsg
} // namespace reinforcement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reinforcement::ResetWorldMsg > {
  static const char* value()
  {
    return "3c2bcf2ff0894cb3058b1bf4c8c4175a";
  }

  static const char* value(const ::reinforcement::ResetWorldMsg&) { return value(); }
};

template<>
struct DataType< ::reinforcement::ResetWorldMsg > {
  static const char* value()
  {
    return "reinforcement/ResetWorldMsg";
  }

  static const char* value(const ::reinforcement::ResetWorldMsg&) { return value(); }
};


// service_traits::MD5Sum< ::reinforcement::ResetWorldMsgRequest> should match 
// service_traits::MD5Sum< ::reinforcement::ResetWorldMsg > 
template<>
struct MD5Sum< ::reinforcement::ResetWorldMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::ResetWorldMsg >::value();
  }
  static const char* value(const ::reinforcement::ResetWorldMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::ResetWorldMsgRequest> should match 
// service_traits::DataType< ::reinforcement::ResetWorldMsg > 
template<>
struct DataType< ::reinforcement::ResetWorldMsgRequest>
{
  static const char* value()
  {
    return DataType< ::reinforcement::ResetWorldMsg >::value();
  }
  static const char* value(const ::reinforcement::ResetWorldMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reinforcement::ResetWorldMsgResponse> should match 
// service_traits::MD5Sum< ::reinforcement::ResetWorldMsg > 
template<>
struct MD5Sum< ::reinforcement::ResetWorldMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reinforcement::ResetWorldMsg >::value();
  }
  static const char* value(const ::reinforcement::ResetWorldMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reinforcement::ResetWorldMsgResponse> should match 
// service_traits::DataType< ::reinforcement::ResetWorldMsg > 
template<>
struct DataType< ::reinforcement::ResetWorldMsgResponse>
{
  static const char* value()
  {
    return DataType< ::reinforcement::ResetWorldMsg >::value();
  }
  static const char* value(const ::reinforcement::ResetWorldMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REINFORCEMENT_MESSAGE_RESETWORLDMSG_H
